-- Enable pg_trgm extension for trigram similarity matching
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Drop tables if they exist (for clean initialization)
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS attachments CASCADE;
DROP TABLE IF EXISTS query_flags CASCADE;
DROP TABLE IF EXISTS query_comments CASCADE;
DROP TABLE IF EXISTS queries CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Queries Table
CREATE TABLE queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_number VARCHAR(50) UNIQUE NOT NULL,
    date_raised TIMESTAMP NOT NULL,
    subject VARCHAR(255) NOT NULL,
    source_link VARCHAR(1024),
    question TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    critical_flag BOOLEAN DEFAULT FALSE NOT NULL,
    assigned_sme_id BIGINT REFERENCES users(id),
    created_by_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Query Comments Table
CREATE TABLE query_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id BIGINT NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id),
    comment_type VARCHAR(20) NOT NULL,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Query Flags Table
CREATE TABLE query_flags (
    query_id BIGINT NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    flag VARCHAR(50) NOT NULL,
    PRIMARY KEY (query_id, flag)
);

-- Attachments Table
CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id BIGINT NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    uploaded_by_id BIGINT NOT NULL REFERENCES users(id),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Audit Logs Table
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    field_name VARCHAR(100),
    old_value TEXT,
    new_value TEXT,
    changed_by_id BIGINT NOT NULL REFERENCES users(id),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Notifications Table
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message VARCHAR(512) NOT NULL,
    query_id BIGINT REFERENCES queries(id) ON DELETE SET NULL,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance and search ranking
CREATE INDEX IF NOT EXISTS idx_queries_source_link ON queries(source_link);
CREATE INDEX IF NOT EXISTS idx_queries_subject_trgm ON queries USING gin (subject gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_queries_question_fts ON queries USING gin (to_tsvector('english', question));

-- Seed default users with bcrypt password hash for 'password'
-- BCrypt hash: $2a$10$gRsiFfb9Hq6bL7A0.B4a1u0U.W0w2Uq7Jb.5F3V1i6d9lFqgH5oE6
INSERT INTO users (name, email, password_hash, role) VALUES
('Default Analyst', 'analyst@example.com', '$2a$10$gRsiFfb9Hq6bL7A0.B4a1u0U.W0w2Uq7Jb.5F3V1i6d9lFqgH5oE6', 'ANALYST'),
('Default SME', 'sme@example.com', '$2a$10$gRsiFfb9Hq6bL7A0.B4a1u0U.W0w2Uq7Jb.5F3V1i6d9lFqgH5oE6', 'SME'),
('Default Admin', 'admin@example.com', '$2a$10$gRsiFfb9Hq6bL7A0.B4a1u0U.W0w2Uq7Jb.5F3V1i6d9lFqgH5oE6', 'ADMIN');
